#!/usr/bin/env npx tsx
/**
 * Generate TypeScript types from the telemetry event registry.
 *
 * Reads: packages/shared/src/telemetry/registry/<namespace>.json
 * Writes:
 *   packages/shared/src/telemetry/generated/event-names.ts  — TelemetryEventName union
 *   packages/shared/src/telemetry/generated/dimensions.ts   — per-event dimension types
 *
 * Usage:
 *   npx tsx scripts/generate-telemetry-types.ts           # write
 *   npx tsx scripts/generate-telemetry-types.ts --check   # fail if files are stale
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { execSync } from "node:child_process";

const REPO_ROOT = path.resolve(import.meta.dirname, "..");
const REGISTRY_DIR = path.join(
  REPO_ROOT,
  "packages/shared/src/telemetry/registry",
);
const OUTPUT_DIR = path.join(
  REPO_ROOT,
  "packages/shared/src/telemetry/generated",
);
const GENERATED_HEADER = `\
// DO NOT EDIT — generated by scripts/generate-telemetry-types.ts
// Run \`npx tsx scripts/generate-telemetry-types.ts\` to regenerate.
`;

// ── Registry types ────────────────────────────────────────────────

interface RegistryDimension {
  name: string;
  type: "string" | "number" | "boolean";
  required: boolean;
  pii: boolean;
  promoted?: boolean;
}

interface RegistryEvent {
  name: string;
  description: string;
  retention_class: "standard" | "sensitive" | "ephemeral";
  dimensions: RegistryDimension[];
}

interface RegistryFile {
  namespace: string;
  events: RegistryEvent[];
}

// ── Load registry ────────────────────────────────────────────────

function loadRegistry(): RegistryEvent[] {
  const files = fs
    .readdirSync(REGISTRY_DIR)
    .filter((f) => f.endsWith(".json"))
    .sort();

  const events: RegistryEvent[] = [];

  for (const file of files) {
    const fullPath = path.join(REGISTRY_DIR, file);
    let parsed: RegistryFile;
    try {
      parsed = JSON.parse(fs.readFileSync(fullPath, "utf-8")) as RegistryFile;
    } catch (e) {
      console.error(`Failed to parse ${file}: ${String(e)}`);
      process.exit(1);
    }
    if (!Array.isArray(parsed.events)) {
      console.error(`${file}: missing "events" array`);
      process.exit(1);
    }
    for (const event of parsed.events) {
      if (!event.name || !event.name.includes(".")) {
        console.error(
          `${file}: event "${event.name}" is not dot-namespaced`,
        );
        process.exit(1);
      }
      events.push(event);
    }
  }

  return events;
}

// ── Codegen helpers ────────────────────────────────────────────────

function eventNameToTypeName(name: string): string {
  return name
    .split(".")
    .map((part) =>
      part
        .split("_")
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
        .join(""),
    )
    .join("");
}

function tsTsType(dimType: RegistryDimension["type"]): string {
  return dimType === "boolean" ? "boolean" : dimType === "number" ? "number" : "string";
}

// ── Generate event-names.ts ────────────────────────────────────────

function generateEventNames(events: RegistryEvent[]): string {
  const names = events.map((e) => `  | ${JSON.stringify(e.name)}`);
  return `${GENERATED_HEADER}
export type TelemetryEventName =
${names.join("\n")};
`;
}

// ── Generate dimensions.ts ────────────────────────────────────────

function generateDimensions(events: RegistryEvent[]): string {
  const interfaceBlocks: string[] = [];
  const mapEntries: string[] = [];

  for (const event of events) {
    const typeName = `${eventNameToTypeName(event.name)}Dimensions`;
    const fields = event.dimensions.map((d) => {
      const tsType = tsTsType(d.type);
      const optional = d.required ? "" : "?";
      const piComment = d.pii ? " // PII — handle with care" : "";
      const promotedComment = d.promoted ? " // promoted ClickHouse column" : "";
      return `  ${d.name}${optional}: ${tsType};${piComment}${promotedComment}`;
    });

    const comment = `/** Dimensions for \`${event.name}\` — ${event.description} */`;
    const iface =
      fields.length > 0
        ? `${comment}\nexport interface ${typeName} {\n${fields.join("\n")}\n}`
        : `${comment}\nexport type ${typeName} = Record<string, never>;`;
    interfaceBlocks.push(iface);
    mapEntries.push(`  ${JSON.stringify(event.name)}: ${typeName};`);
  }

  return `${GENERATED_HEADER}
${interfaceBlocks.join("\n\n")}

/**
 * Maps each registered event name to its declared dimension interface.
 * Use for IDE autocomplete when constructing v2 envelope events.
 */
export type TelemetryEventDimensions = {
${mapEntries.join("\n")}
};
`;
}

// ── Main ──────────────────────────────────────────────────────────

const checkMode = process.argv.includes("--check");

const events = loadRegistry();
console.log(`Loaded ${events.length} events from registry.`);

fs.mkdirSync(OUTPUT_DIR, { recursive: true });

const eventNamesContent = generateEventNames(events);
const dimensionsContent = generateDimensions(events);

const eventNamesPath = path.join(OUTPUT_DIR, "event-names.ts");
const dimensionsPath = path.join(OUTPUT_DIR, "dimensions.ts");

if (checkMode) {
  let stale = false;

  for (const [filePath, content] of [
    [eventNamesPath, eventNamesContent],
    [dimensionsPath, dimensionsContent],
  ] as [string, string][]) {
    const relative = path.relative(REPO_ROOT, filePath);
    if (!fs.existsSync(filePath)) {
      console.error(`STALE: ${relative} does not exist. Run: npx tsx scripts/generate-telemetry-types.ts`);
      stale = true;
    } else {
      const existing = fs.readFileSync(filePath, "utf-8");
      if (existing !== content) {
        console.error(`STALE: ${relative} is out of date. Run: npx tsx scripts/generate-telemetry-types.ts`);
        stale = true;
      }
    }
  }

  if (stale) {
    process.exit(1);
  }
  console.log("Generated telemetry types are up to date.");
} else {
  fs.writeFileSync(eventNamesPath, eventNamesContent, "utf-8");
  console.log(`Wrote ${path.relative(REPO_ROOT, eventNamesPath)}`);

  fs.writeFileSync(dimensionsPath, dimensionsContent, "utf-8");
  console.log(`Wrote ${path.relative(REPO_ROOT, dimensionsPath)}`);
}
